package model

import (
	"github.com/naoina/genmai"
)

type Post struct {
	Id int64 `db:"pk" json:"id"`
	Title string `default:""`
	Content string `default:""`
	genmai.TimeStamp
}

func (m *Post) BeforeInsert() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return m.TimeStamp.BeforeInsert()
}

func (m *Post) AfterInsert() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return nil
}

func (m *Post) BeforeUpdate() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return m.TimeStamp.BeforeUpdate()
}

func (m *Post) AfterUpdate() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return nil
}

func (m *Post) BeforeDelete() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return nil
}

func (m *Post) AfterDelete() error {
	// FIXME: This method is auto-generated by Kocha.
	//        You can remove this method if unneeded.
	return nil
}
