package controller

import (
	"github.com/naoina/kocha"
	"fmt"
	"kocha-sample/db"
	"kocha-sample/app/model"
)

type Post struct {
	*kocha.DefaultController
}

func (po *Post) GET(c *kocha.Context) error {
	// FIXME: auto-generated by kocha
	fmt.Println("post GET called\n")
	
	var posts []model.Post
	err := db.Get("default").Select(&posts)
	fmt.Printf("select err: %v\n", err)
  if err != nil {
   	return c.RenderError(500, nil, nil)
  }

  for key, value := range posts {
    fmt.Printf("sample post %d: %v\n", key, value.Title)
	}

	return c.Render(map[string]interface{}{
		"ControllerName": "Post",
		"posts": posts,
	})
}

func (po *Post) POST(c *kocha.Context) error {
	// FIXME: auto-generated by kocha
	fmt.Println("post POST called\n")

	title := c.Params.Get("title")
	content := c.Params.Get("content")

	fmt.Printf("check params. title: %s content: %s\n", title, content)
	obj := &model.Post{
		Title: title,
		Content: content,
	}
	n, err := db.Get("default").Insert(obj)
	fmt.Printf("insert n: %d\n", n)
	fmt.Printf("insert err: %v\n", err)
	if err != nil {
		return c.RenderError(500, nil, nil)
	}

	return c.Redirect("/post", false)
}
