package controller

import (
	"github.com/naoina/kocha"
	"fmt"
	"kocha-sample/db"
	"kocha-sample/app/model"
)

type Post struct {
	*kocha.DefaultController
}

func (this *Post) GET(c *kocha.Context) error {
	// FIXME: auto-generated by kocha
	fmt.Println("post GET called\n")
	
	var posts []model.Post
	err := db.Get("default").Select(&posts)
	fmt.Printf("select err: %v\n", err)
  if err != nil {
   	return c.RenderError(500, nil, nil)
  }

  fmt.Printf("posts all %#v\n", posts)

  for key, value := range posts {
    fmt.Printf("sample post %d: %#v\n", key, value)
	}

	return c.Render(map[string]interface{}{
		"ControllerName": "Post",
		"posts": posts,
	})
}

func (this *Post) POST(c *kocha.Context) error {
	// FIXME: auto-generated by kocha
	fmt.Println("post POST called\n")

	title := c.Params.Get("title")
	content := c.Params.Get("content")

	fmt.Printf("check params. title: %s content: %s\n", title, content)
	obj := &model.Post{
		Title: title,
		Content: content,
	}
	n, err := db.Get("default").Insert(obj)
	fmt.Printf("insert n: %d\n", n)
	fmt.Printf("insert err: %#v\n", err)
	if err != nil {
		return c.RenderError(500, nil, nil)
	}

	return c.Redirect("/post", false)
}


// PostDetail Controller
type PostDetail struct {
	*kocha.DefaultController
}

func (this *PostDetail) GET(c *kocha.Context) error {
	// FIXME: auto-generated by kocha
	fmt.Println("PostDetail GET called\n")

	id := c.Params.Get("id")

	var posts []model.Post
	err := db.Get("default").Select(&posts, db.Get("default").Where("id", "=", id))
	fmt.Printf("select err: %v\n", err)
  if err != nil {
   	return c.RenderError(500, nil, nil)
  }

  fmt.Printf("posts all %#v\n", posts)

  if len(posts) != 1 {
		return c.RenderError(404, nil, nil)  	
  }

	return c.Render(map[string]interface{}{
		"ControllerName": "PostDetail",
		"post": posts[0],
	})
}

// PostEdit Controller
type PostEdit struct {
	*kocha.DefaultController
}

func (this *PostEdit) GET(c *kocha.Context) error {
	// FIXME: auto-generated by kocha
	fmt.Println("post PostEdit GET called\n")

	id := c.Params.Get("id")

	var posts []model.Post
	err := db.Get("default").Select(&posts, db.Get("default").Where("id", "=", id))
	fmt.Printf("select err: %v\n", err)
  if err != nil {
   	return c.RenderError(500, nil, nil)
  }

  fmt.Printf("posts all %#v\n", posts)

  if len(posts) != 1 {
		return c.RenderError(404, nil, nil)  	
  }

	return c.Render(map[string]interface{}{
		"ControllerName": "PostEdit",
		"post": posts[0],
	})
}

func (this *PostEdit) POST(c *kocha.Context) error {
	// FIXME: auto-generated by kocha
	fmt.Println("post PostEdit POST called\n")

	id := c.Params.Get("id")
	title := c.Params.Get("title")
	content := c.Params.Get("content")

	var posts []model.Post
	err := db.Get("default").Select(&posts, db.Get("default").Where("id", "=", id))
	fmt.Printf("select err: %v\n", err)
  if err != nil {
   	return c.RenderError(500, nil, nil)
  }

  fmt.Printf("posts all %#v\n", posts)

  if len(posts) != 1 {
		return c.RenderError(404, nil, nil)  	
  }

  obj := posts[0]
  obj.Title = title
  obj.Content = content

  count, updateError := db.Get("default").Update(&obj)

  fmt.Printf("update err: %v\n", updateError)
  fmt.Printf("update count: %v\n", count)

	return c.Redirect(fmt.Sprintf("/post/%s", id), false)
}

